#!/usr/bin/env bash

kubectl delete secret cflt-cluster-ca-cert
kubectl delete secret cflt-clients-ca-cert

kubectl create secret generic cflt-clients-ca-cert \
  --from-file=ca.crt=ca.crt

kubectl create secret generic cflt-cluster-ca-cert \
  --from-file=ca.crt=ca.crt \
  --from-file=ca.p12=ca.p12 \
  --from-literal=ca.password=P12-PASSWORD


kubectl delete secret cflt-clients-ca
kubectl delete secret cflt-cluster-ca


kubectl create secret generic cflt-clients-ca \
    --from-file=ca.key=ca.key

kubectl create secret generic cflt-cluster-ca \
    --from-file=ca.key=ca.key

## label the secrets

kubectl label secret cflt-clients-ca-cert \
        strimzi.io/kind=Kafka strimzi.io/cluster=cflt

kubectl label secret cflt-clients-ca \
        strimzi.io/kind=Kafka strimzi.io/cluster=cflt

kubectl label secret cflt-cluster-ca-cert \
        strimzi.io/kind=Kafka strimzi.io/cluster=cflt

kubectl label secret cflt-cluster-ca \
        strimzi.io/kind=Kafka strimzi.io/cluster=cflt

## add annotations

###
# If you are replacing CA certificates automatically generated by the Cluster Operator,
# use the next higher incremental value from the existing annotation and follow the
# replacing CA keys procedure. If there are no CA certificates automatically generated
# by the Cluster Operator, start from 0 (zero) as the incremental value
# (strimzi.io/ca-cert-generation=0) for your own CA certificate.
# Set a higher incremental value when you renew the certificates.
###

kubectl annotate secret cflt-clients-ca-cert \
        strimzi.io/ca-cert-generation=1

kubectl annotate secret cflt-clients-ca \
        strimzi.io/ca-key-generation=1

kubectl annotate secret cflt-cluster-ca-cert \
        strimzi.io/ca-cert-generation=1

kubectl annotate secret cflt-cluster-ca \
        strimzi.io/ca-key-generation=1
