---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: s3sink
  namespace: confluent
spec:
  class: "io.confluent.connect.s3.S3SinkConnector"
  taskMax: 4
  connectClusterRef:
    name: connect
  configs:
    topics: "pageviews"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    s3.bucket.name: "purbon-conn"
    s3.region: "us-east-1"
    flush.size: "1"
    aws.access.key.id: "${file:/mnt/secrets/s3-credentials/custom.properties:key.id}" 
    aws.secret.access.key: "${file:/mnt/secrets/s3-credentials/custom.properties:access.key}" 