---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo-topic
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 4
  configs:
    cleanup.policy: "delete"
  kafkaRestClassRef:
    name:  my-kafka-rest