---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: BAh7uHGNo2czKNrwkDg5ccuItEcoiwBxOG7OrkgphUQ
  namespace: confluent
spec:
  principal:
    type: group
    name: /g1
  role: ClusterAdminkub