- job_name: Confluent Cloud
  scrape_interval: 1m
  scrape_timeout: 1m
  honor_timestamps: true
  static_configs:
    - targets:
      - api.telemetry.confluent.cloud
  scheme: https
  basic_auth:
    username: changeme
    password: changeme
  metrics_path: /v2/metrics/cloud/export
  params:
      "resource.kafka.id":
        - changeme
      "resource.schema_registry.id":
        - changeme
      "resource.ksql.id":
        - changeme
      "resource.connector.id":
        - changeme
