apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kafkamon
  namespace: monitoring
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector: 
    matchLabels:
      name: confluent
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager
      port: web
