apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: confluent
  namespace: monitoring
  labels:
    onfluent-platform: "true"
spec:
  selector:
    matchLabels:
      confluent-platform: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: prometheus
