{
 "title": "Confluent Cloud",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes, kafka_id)"
    }
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Kafka Clusters",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (confluent_kafka_server_partition_count)"
    }
   ]
  },
  {
   "title": "Total Connectors",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(confluent_kafka_connect_sent_bytes)"
    }
   ]
  },
  {
   "title": "Total ksqlDB Clusters",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(confluent_kafka_ksql_streaming_unit_count)"
    }
   ]
  },
  {
   "title": "Total Schema Registry Instances",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "confluent_kafka_schema_registry_schema_count",
     "legendFormat": "{{schema_registry_id}}"
    }
   ]
  },
  {
   "title": "Retained bytes ",
   "type": "stat",
   "description": "Basic clusters have a max retained bytes limit of 5 TB prior to replication. ccloud_metrics_retained_bytes is after replication thus needs to be divided by 3.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_retained_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"})/3",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Write on topics (rate)",
   "type": "timeseries",
   "description": "Per-second average rate of ingress of data to topics, basic cluster has a max of 100MBps.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(confluent_kafka_server_received_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Read of topics (rate)",
   "type": "timeseries",
   "description": "Per-second average rate of egress data to topics, basic cluster has a max of 100MBps.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(confluent_kafka_server_sent_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Requests (rate)",
   "type": "stat",
   "description": "Per-second average rate of requests, basic cluster maxes out at 1500 requests per second.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(confluent_kafka_server_request_count{type=~\".*\", kafka_id=~\"$cluster\"}[1m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Avg. Active connections",
   "type": "stat",
   "description": "The average active connections to a cluster. Basic clusters limit active connections to 1000.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(confluent_kafka_server_active_connection_count{kafka_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Partition count ",
   "type": "timeseries",
   "description": "The sum of partitions in a cluster. Basic cluster max partitions limit is 2048.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "confluent_kafka_server_partition_count{kafka_id=~\"$cluster\"}",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Partition count change (delta)",
   "type": "timeseries",
   "description": "Basic clusters have a limit on the number of partitions that can be created and deleted in a 5 minute period. This single stat provides the absolute difference between the number of partitions are the beginning and end of the 5 minute period. This over simplifies the problem, so more conservative thresholds are put in place. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "abs(delta(confluent_kafka_server_partition_count{kafka_id=~\"$cluster\"}[5m]))",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Authentication Rate",
   "type": "timeseries",
   "description": "The average active connections to a cluster. Basic clusters limit active connections to 1000.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "confluent_kafka_server_successful_authentication_count",
     "legendFormat": "{{principal_id}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topic retained bytes",
   "type": "graph",
   "description": "The current count of bytes retained by the cluster, summed across all partitions. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kafka_id, topic) (confluent_kafka_server_retained_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{kafka_id}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Topic received bytes",
   "type": "graph",
   "description": "The delta count of bytes received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic Sent bytes",
   "type": "graph",
   "description": "The delta count of bytes sent over the network. Each sample is the number of bytes sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic received record",
   "type": "graph",
   "description": "The delta count of records received. Each sample is the number of records received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_records{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic sent records",
   "type": "graph",
   "description": "The delta count of records sent. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_records{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "description": "The delta count of requests received over the network. Each sample is the number of requests received since the previous data point. The count sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_kafka_server_request_count{kafka_id=~\"$cluster\"}",
     "legendFormat": "{{kafka_id}}-{{type}}"
    }
   ]
  },
  {
   "title": "Connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sent records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_kafka_connect_sent_records{connector_id=~\"$cluster\"}",
     "legendFormat": "{{connector_id}} -- {{connector_id}}"
    }
   ]
  },
  {
   "title": "Received bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_kafka_connect_received_bytes{connector_id=~\"$cluster\"}",
     "legendFormat": "{{connector_id}} -- {{connector_id}}"
    }
   ]
  },
  {
   "title": "Dead Letter Queue bytes",
   "type": "graph",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_kafka_connect_dead_letter_queue_records{connector_id=~\"$cluster\"}",
     "legendFormat": "{{connector_id}}"
    }
   ]
  },
  {
   "title": "Sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_kafka_connect_sent_bytes{connector_id=~\"$cluster\"}",
     "legendFormat": "{{connector_id}} -- {{connector_id}}"
    }
   ]
  },
  {
   "title": "Received records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_kafka_connect_received_records{connector_id=~\"$cluster\"}",
     "legendFormat": "{{connector_id}} -- {{connector_id}}"
    }
   ]
  },
  {
   "title": "ksqlDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ksqlDB streaming unit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "confluent_kafka_ksql_streaming_unit_count",
     "legendFormat": "{{ksql_id}}"
    }
   ]
  },
  {
   "title": "ksqlDB application count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(confluent_kafka_ksql_streaming_unit_count)"
    }
   ]
  },
  {
   "title": "Metrics API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"Confluent Cloud\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}