---
apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlinkv2-demo-dest
  namespace: confluent
spec:
  name: clusterlinkingv2
  sourceInitiatedLink:
    linkMode: Destination
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: krc-cloud
      namespace: confluent
  sourceKafkaCluster:
    kafkaRestClassRef:
      name: my-kafka-restv2
      namespace: confluent
  mirrorTopics:
    - name: demo-topicv2